CREATE TABLE foodora_restaurant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    restaurant_name TEXT NOT NULL,
    restaurant_address TEXT NOT NULL,
    city TEXT NOT NULL,
    zip TEXT NOT NULL,
    state TEXT,
    phone TEXT,
    url TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);

