CREATE TABLE restaurant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    restaurant_name TEXT NOT NULL,
    restaurant_address TEXT NOT NULL,
    city TEXT NOT NULL,
    zip INTEGER NOT NULL,
    state TEXT,
    phone INTEGER,
    url TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);