CREATE TABLE foodora_dish (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dish_name TEXT NOT NULL,
    restaurant_id INTEGER
        REFERENCES foodora_restaurant(id) ON DELETE CASCADE NOT NULL,
    price INTEGER NOT NULL 
);

