CREATE TABLE foodora_dish_has_tag (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dish_id INTEGER
        REFERENCES foodora_dish(id) ON DELETE CASCADE NOT NULL,
    tag_id INTEGER
        REFERENCES foodora_tag(id) ON DELETE CASCADE NOT NULL,
    test TEXT,
    UNIQUE(dish_id, tag_id)
);